name: edumaster
description: "Aplikasi Wali Kelas dan Guru Mapel"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  pdf: ^3.10.4
  printing: ^5.11.1
  intl: ^0.19.0
  geolocator: ^10.1.0
  image_picker: ^1.0.7
  url_launcher: ^6.2.4
  file_picker: ^8.0.0
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true